version: '2.2'
services:
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:8.4.0
    container_name: elasticsearch
    volumes:
      - elasticsearch-data:/usr/share/elasticsearch/data
    ports:
      - 9200:9200
    restart: always
    environment:
      - xpack.security.enabled=false
      - xpack.security.authc.api_key.enabled=false
      - xpack.reporting.kibanaServer.hostname=localhost
      - discovery.type=single-node
    ulimits:
      memlock:
        soft: -1
        hard: -1
    mem_limit: 4g

  kibana:
    depends_on:
      - elasticsearch
    image: docker.elastic.co/kibana/kibana:8.4.0
    container_name: kibana
    volumes:
      - kibana-data:/usr/share/kibana/data
    ports:
      - 5601:5601
    restart: always
    environment:
      - ELASTICSEARCH_HOSTS=http://elasticsearch:9200
    mem_limit: 1g

  logstash:
    image: docker.elastic.co/logstash/logstash:8.4.0
    container_name: logstash
    depends_on:
      - elasticsearch
    volumes:
      - ./logstash.yml:/usr/share/logstash/config/logstash.yml
      - ./logstash.conf:/usr/share/logstash/pipeline/logstash.conf
    ports:
      - 5044:5044  
      - 9600:9600 # For Logstash TCP/UDP input (can be used for other log shippers)
    environment:
      - ELASTICSEARCH_HOST=http://elasticsearch:9200
    restart: always
    mem_limit: 3g
    ulimits:
      memlock:
        soft: -1
        hard: -1

  logstash-exporter:
    build: .
    container_name: persia
    depends_on: 
      - logstash
    ports:
      - 9124:9124
    restart: unless-stopped
    

volumes:
  elasticsearch-data:
    driver: local
  kibana-data:
    driver: local